# Utiliser l'image officielle de Nginx comme base
FROM nginx:latest

# Copier les fichiers du site dans le répertoire par défaut de Nginx
COPY ./html /usr/share/nginx/html

# Exposer le port 80
EXPOSE 80