version: "3.9"
services:
  web:
    build: ../frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ../backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  db:
    image: mariadb:10.6 # ou mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
